const titlesList = [
  "Honor of King: Chapter of Glory",
  "THE BURNING MAN (HUO SHEN: TIANQI ZHIZI)",
  "The Sword Fairy is Here",
  "Da Wang Rao Ming (Spare Me, Great Lord!)",
  "Law Of The Devil",
  "Since The Red Moon Appeared (Cong Hong Yue Kaishi)",
  "The Eternal Strife",
  "The Invincible",
  "The Legend of the Taiyi Sword Immortal",
  "Againts The Gods",
  "The Age of Cosmos Exploration",
  "Otherworldly Evil Monarch (Yi Ren Jun Moye)",
  "The Proud Emperor of Eternity",
  "The Metaverse (Baijia Jue: Jianghu Gui Shi Lu)",
  "Ancient Lords (Yishi Zhi Zun)",
  "The Great Ruller",
  "The Secrets of Star Divine Arts",
  "Blader Soul (Bu Xing Si)",
  "Star Lord of God and Dragon (Dragon Star Master)",
  "Sage Ancestor",
  "The Abyss Game (Fatal Rule)",
  "THE RICH GOD",
  "Villain Initialization (Fanpai Chushihua)",
  "Wu Ying sanqian Dao",
  "Back to the Great Ming",
  "Wind Rises In Jinling",
  "Star Lord of God and Dragon (Dragon Star Master)", // Duplicate title
  "The Island Of Siliang",
  "Hidden Sect Leader",
  "The charm of soul pets (Huan Chong Shi)",
  "Perfect world movie",
  "Legend of Sho",
  "The Golden Wug",
  "Legend of Soldier",
  "King of Loose Cultivators",
  "Dragon Prince Yuan (Yuan Zun)",
  "Slay The Gods (Zhan Shen)",
  "A Momment But Forever",
  "My Heroic Husband",
  "I Can Experience Limitless Enlightements",
  "Heavenly Brick Knight",
  "Immortality",
  "Martial God Asura",
  "APOTHEOSIS",
  "Soul Land Season 2 (Live Action)",
  "SWALLOWED STAR MOVIE : XUELUO CONTINENT",
  "Adventures in Subduing the Demons",
  "The Legend of Sky Lord",
  "I Can Have Infinite Enlightenment",
  "My WeChat Connects to the Dragon Palace",
  "The Path Toward Heaven",
  "Renjian Zui Deyi (Proud Swordsman)",
  "Keyboard Immortal",
  "Glorious Revenge of Ye Feng",
  "Jian Lai (Sword coming)",
  "God of War Alliance",
  "Heaven Shadow",
  "Wu Dong Qian Kun",
  "Tomb of Fallen Gods",
  "The War of Cards",
  "Xi Xing Ji",
  "Over Goddess",
  "The Demon King Who Lost His Job",
  "Tiger x Crane: Record of the Demon Master",
  "Fengwu Demon Chef",
  "The World of Immortals (Chang Sheng Jie)",
  "Solo Leveling: Arise from the Shadow",
  "Martial Invers",
  "Martial Peak",
  "Nirvana of Storm Riders",
  "The Ravages of Time",
  "Rebirth of the Sword Patriarch",
  "Throne of Seal Movie: Electrolux",
  "Endless God Realm",
  "The Legend of Pricess Chang-Ge",
  "Lord of Destiny",
  "Supreme Sword God",
  "The Super Cube (Chao Neng Lifang: Chaofan Pian)",
  "GoWest: Overworked",
  "Everything Is Fine With The Emperor",
  "Honor of Kings",
  "My Senior Brother is Too Strong",
  "Divine Dao Emperor",
  "My Sectarian Members Are Spies",
  "Fight For The Throne",
  "Battle Through the heaven",
  "A Record of Mortal to Immortality",
  "Legend Of Martial",
  "Tales of Herding Gods",
  "Renegade Immortal",
  "Jun You Yun",
  "Swallowed Star",
  "Over the Divine Kingdom",
  "Wukong (Great Ape Soul)",
  "Stellar Transformation",
  "Rich Player",
  "Martial Master",
  "100.000 Years Of Refining Qi",
  "Peerless Battle Spirit",
  "Shrouding the Heavens",
  "Heaven Swallowing Record (Tun Tian Ji)",
  "Urban Ancient Immortal Doctor",
  "Throne of Seal",
  "Jade Dinasty",
  "Little Fairy Yao",
  "My Senior Brother is Too Ready",
  "Perfect World",
  "The All-devouring Whale: Homecoming",
  "EMBERS",
  "Ancient War Soul",
  "Azure Legacy",
  "Lingwu Continent",
  "Supreme Alchemy",
  "Soul Land S1 & S2",
];
export default titlesList;
